# Generated by Django 5.2.18 on 2026-10-06 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(choices=[('VILLA_LIBERTAD', 'Villa Libertad'), ('LAS_AMERICAS', 'Las Américas')], max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counted_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('counted_amount_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares')], max_length=3)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='cash_sessions.cashsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('user',), name='unique_open_cash_session_per_user'),
        ),
    ]
