# Generated by Django 5.2.18 on 2026-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(choices=[('VILLA_LIBERTAD', 'Villa Libertad'), ('LAS_AMERICAS', 'Las Américas')], max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'branch inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('VILLA_LIBERTAD', 'Villa Libertad'), ('LAS_AMERICAS', 'Las Américas')], max_length=20)),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('SALE', 'Venta'), ('WASTE', 'Merma'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('LIQUIDS', 'Líquidos'), ('POWDERS', 'Polvos'), ('ACCESSORIES', 'Accesorios')], max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('LITER', 'Litro'), ('KILOGRAM', 'Kilogramo'), ('UNIT', 'Unidad')], max_length=20)),
                ('cost_price_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_price_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
