# Generated by Django 5.2.18 on 2026-10-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price_usd__gte', 0)), name='product_cost_price_usd_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price_usd__gte', 0)), name='product_sale_price_usd_gte_0'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='branchinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_inventories', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['branch', 'product', 'created_at'], name='inv_mov_branch_prod_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchinventory',
            constraint=models.UniqueConstraint(fields=('product', 'branch'), name='unique_branch_inventory_product_branch'),
        ),
        migrations.AddConstraint(
            model_name='branchinventory',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='branch_inventory_current_stock_gte_0'),
        ),
    ]
