# Generated by Django 5.2.18 on 2026-10-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branches_from_existing_data'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchinventory',
            name='branch',
            field=models.ForeignKey(db_column='branch', on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='branches.branch', to_field='code'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='branch',
            field=models.ForeignKey(db_column='branch', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='branches.branch', to_field='code'),
        ),
    ]
