# Generated by Django 5.2.18 on 2026-10-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_ves_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['-created_at'], name='exchange_rate_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('usd_to_ves_rate__gt', 0)), name='exchange_rate_usd_to_ves_rate_gt_0')],
            },
        ),
    ]
