# Generated by Django 5.2.18 on 2026-10-06 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('BCV', 'BCV')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to=settings.AUTH_USER_MODEL),
        ),
    ]
