# Generated by Django 5.2.18 on 2026-10-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_sessions', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(choices=[('VILLA_LIBERTAD', 'Villa Libertad'), ('LAS_AMERICAS', 'Las Américas')], max_length=20)),
                ('customer_tax_id', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('exchange_rate_at_invoice', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_ves', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cash_sessions.cashsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('POS_CARD', 'Punto de venta'), ('CASH_VES', 'Efectivo VES'), ('CASH_USD', 'Efectivo USD'), ('MOBILE_PAYMENT', 'Pago móvil')], max_length=20)),
                ('currency', models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approval_reference', models.CharField(blank=True, max_length=50)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'created_at'], name='sale_branch_created_idx'),
        ),
    ]
