# Generated by Django 5.2.18 on 2026-10-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branches_from_existing_data'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(db_column='branch', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch', to_field='code'),
        ),
    ]
