# Generated by Django 5.2.18 on 2026-10-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assigned_branch_nullable'),
        ('branches', '0002_branches_from_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, db_column='assigned_branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='branches.branch', to_field='code'),
        ),
    ]
